name: health_connect
description: An integrated health management app.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.0
  http: ^1.2.2
  flutter_lints: ^4.0.0
  google_sign_in: ^6.2.1
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  flutter_chat_ui: ^1.6.15
  flutter_chat_types: ^3.6.2
  permission_handler: ^11.3.1
  audioplayers: ^6.1.0
  firebase_core_web: ^2.18.1
  flutter_svg: ^2.0.13
  cached_network_image: ^3.4.1

  google_maps_flutter: ^2.9.0
  geolocator: ^9.0.0
  url_launcher: ^6.0.17
  table_calendar: ^3.0.7
  firebase_ui_auth: any
  firebase_ui_oauth_google: any
  json_annotation: ^4.9.0
  json_serializable: ^6.8.0
  device_info_plus: ^10.1.2
  path_provider: ^2.0.15
  intl: ^0.19.0
  csv: ^5.0.0
  email_validator: ^2.0.1
  pdf: ^3.6.0
  firebase_database: ^11.1.4
  printing: ^5.9.0
  flutter_animate: ^4.5.0
  firebase_messaging: ^15.1.3
  lottie: ^3.1.3
  shared_preferences: ^2.3.2
  rx_shared_preferences: ^4.0.0
  lucide_icons: ^0.257.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.13
  flutter_launcher_icons: ^0.14.1

# Flutter Launcher Icons configuration
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo1.png"
  adaptive_icon_background: "#ffffff" # Optional: Background color for adaptive icons
  adaptive_icon_foreground: "assets/images/logo.png" # Optional: Foreground image for adaptive icons
  min_sdk_android: 21 # Optional: Minimum SDK version for Android
  web:
    generate: true
    image_path: "assets/images/logo1.png"
    background_color: "#ffffff"
    theme_color: "#ffffff"
  windows:
    generate: true
    image_path: "assets/images/logo1.png"
    icon_size: 48 # Optional: Icon size for Windows
  macos:
    generate: true
    image_path: "assets/images/logo1.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
    - assets/images/google.png
    - assets/images/onboarding1.png
    - assets/images/onboarding3.png
    - assets/images/apple.png
    - assets/locations.json
    - assets/images/logo1.png
    - assets/images/onboarding2.jpeg
    - assets/images/doctor_image.png
    - assets/images/justice_image.jpeg