// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbdZOg_g8Fc3_s_sKyk7mAtgR5ns2m42Y',
    appId: '1:151546515188:web:ad752d23583059bdfcd8a1',
    messagingSenderId: '151546515188',
    projectId: 'health-hub-3cc83',
    authDomain: 'health-hub-3cc83.firebaseapp.com',
    storageBucket: 'health-hub-3cc83.firebasestorage.app',
    measurementId: 'G-QXYJXPQ695',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBytGvmVivePb0MaIHWZ4JEIS4fAlpgkCY',
    appId: '1:151546515188:android:dd21897177872ec2fcd8a1',
    messagingSenderId: '151546515188',
    projectId: 'health-hub-3cc83',
    storageBucket: 'health-hub-3cc83.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0eHNF2IAuktT-uLXvYAQcW-CZoj-h564',
    appId: '1:151546515188:ios:70d820ea028fb7e1fcd8a1',
    messagingSenderId: '151546515188',
    projectId: 'health-hub-3cc83',
    storageBucket: 'health-hub-3cc83.firebasestorage.app',
    iosBundleId: 'com.example.healthHub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0eHNF2IAuktT-uLXvYAQcW-CZoj-h564',
    appId: '1:151546515188:ios:70d820ea028fb7e1fcd8a1',
    messagingSenderId: '151546515188',
    projectId: 'health-hub-3cc83',
    storageBucket: 'health-hub-3cc83.firebasestorage.app',
    iosBundleId: 'com.example.healthHub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBbdZOg_g8Fc3_s_sKyk7mAtgR5ns2m42Y',
    appId: '1:151546515188:web:59097507f4cedb92fcd8a1',
    messagingSenderId: '151546515188',
    projectId: 'health-hub-3cc83',
    authDomain: 'health-hub-3cc83.firebaseapp.com',
    storageBucket: 'health-hub-3cc83.firebasestorage.app',
    measurementId: 'G-C58S0LF7BS',
  );
}
